version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
      
  user-service:
    build: ./backend/user-service
    ports:
      - "3001:3001"

  cart-service:
    build: ./backend/cart-service
    ports:
      - "3003:3003"

  order-service:
    build: ./backend/order-service
    ports:
      - "3004:3004"

  product-service:
    build: ./backend/product-service
    ports:
      - "3002:3002"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
